spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: mysqlDemo
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/test?useSSL=true&requireSSL=false'
    username: 'test'
    password: 'test'
  jpa:
    open-in-view: true

logging:
  level:
    com.example: debug
    com.mysql: debug
    org:
      springframework.data: debug
      hibernate: debug
